package com.example.admin.pandatv.model.modelutils.pandalive_greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.admin.pandatv.model.modelutils.pandalive_greendao.LookTalkBean;

import com.example.admin.pandatv.model.modelutils.pandalive_greendao.LookTalkBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lookTalkBeanDaoConfig;

    private final LookTalkBeanDao lookTalkBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lookTalkBeanDaoConfig = daoConfigMap.get(LookTalkBeanDao.class).clone();
        lookTalkBeanDaoConfig.initIdentityScope(type);

        lookTalkBeanDao = new LookTalkBeanDao(lookTalkBeanDaoConfig, this);

        registerDao(LookTalkBean.class, lookTalkBeanDao);
    }
    
    public void clear() {
        lookTalkBeanDaoConfig.getIdentityScope().clear();
    }

    public LookTalkBeanDao getLookTalkBeanDao() {
        return lookTalkBeanDao;
    }

}
