package com.example.admin.pandatv.model.modelutils.chinalive_greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDao_China_TabDaoConfig;

    private final GreenDao_China_TabDao greenDao_China_TabDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDao_China_TabDaoConfig = daoConfigMap.get(GreenDao_China_TabDao.class).clone();
        greenDao_China_TabDaoConfig.initIdentityScope(type);

        greenDao_China_TabDao = new GreenDao_China_TabDao(greenDao_China_TabDaoConfig, this);

        registerDao(GreenDao_China_Tab.class, greenDao_China_TabDao);
    }
    
    public void clear() {
        greenDao_China_TabDaoConfig.clearIdentityScope();
    }

    public GreenDao_China_TabDao getGreenDao_China_TabDao() {
        return greenDao_China_TabDao;
    }

}
