package com.example.admin.pandatv.model.modelutils.chinalive_greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.admin.pandatv.model.modelutils.chinalive_greendao.GreenDao_China_Tab;
import com.example.admin.pandatv.model.modelutils.pandalive_greendao.LookTalkBean;

import com.example.admin.pandatv.model.modelutils.chinalive_greendao.GreenDao_China_TabDao;
import com.example.admin.pandatv.model.modelutils.pandalive_greendao.LookTalkBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDao_China_TabDaoConfig;
    private final DaoConfig lookTalkBeanDaoConfig;

    private final GreenDao_China_TabDao greenDao_China_TabDao;
    private final LookTalkBeanDao lookTalkBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDao_China_TabDaoConfig = daoConfigMap.get(GreenDao_China_TabDao.class).clone();
        greenDao_China_TabDaoConfig.initIdentityScope(type);

        lookTalkBeanDaoConfig = daoConfigMap.get(LookTalkBeanDao.class).clone();
        lookTalkBeanDaoConfig.initIdentityScope(type);

        greenDao_China_TabDao = new GreenDao_China_TabDao(greenDao_China_TabDaoConfig, this);
        lookTalkBeanDao = new LookTalkBeanDao(lookTalkBeanDaoConfig, this);

        registerDao(GreenDao_China_Tab.class, greenDao_China_TabDao);
        registerDao(LookTalkBean.class, lookTalkBeanDao);
    }
    
    public void clear() {
        greenDao_China_TabDaoConfig.getIdentityScope().clear();
        lookTalkBeanDaoConfig.getIdentityScope().clear();
    }

    public GreenDao_China_TabDao getGreenDao_China_TabDao() {
        return greenDao_China_TabDao;
    }

    public LookTalkBeanDao getLookTalkBeanDao() {
        return lookTalkBeanDao;
    }

}
